services:
  tailscale:
    extends:
      file: ../../shared/tailscale.yaml
      service: tailscale
    hostname: yamtrack
  yamtrack:
    container_name: yamtrack
    image: ghcr.io/fuzzygrim/yamtrack
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - TZ=America/New_York
      - SECRET=longstring
      - REDIS_URL=redis://redis:6379
    volumes:
      - ${SSD_DATA_LOC:?error}/${COMPOSE_PROJECT_NAME}/db/state:/yamtrack/db
    network_mode: service:tailscale

  redis:
    container_name: yamtrack-redis
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - ${SSD_DATA_LOC:?error}/${COMPOSE_PROJECT_NAME}/redis/state:/data